FROM node:14-alpine as build-stage
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
COPY package.json ./
COPY package-lock.json ./
RUN npm install
COPY ./src ./src/
COPY ./public ./public/
COPY ./nginx-ssl/default.conf /etc/nginx/conf.d/default.conf
RUN npm run build

FROM nginx:stable-alpine    
COPY --from=build-stage /app/build/ /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
