dist: focal
language: bash
branches:
    only:
        - main
script:
  - docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
  - sudo apt-get -y update
  - sudo apt-get -y install jq
  - cat <<< $(jq '.+{"experimental":"enabled"}' ~/.docker/config.json) > ~/.docker/config.json
  - echo "$(docker version -f '{{.Server.Experimental}}')"
  - DOCKER_CLI_EXPERIMENTAL=enabled bash build.sh