dist: focal
language: bash
branches:
    only:
        - main
script:
  - docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
  - echo "$(docker version -f '{{.Server.Experimental}}')"
  - DOCKER_CLI_EXPERIMENTAL=enabled bash build.sh