dist: bionic
language: bash
branches:
    only:
        - main
before_install:
  - sudo apt purge --auto-remove qemu-user qemu-user-binfmt binfmt-support
  - sudo apt install qemu-user
  - sudo rm -rf /var/lib/apt/lists/*
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) edge"
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
  - mkdir -vp ~/.docker/cli-plugins/
  - curl --silent -L "https://github.com/docker/buildx/releases/download/v0.5.1/buildx-v0.5.1.linux-amd64" > ~/.docker/cli-plugins/docker-buildx
  - chmod a+x ~/.docker/cli-plugins/docker-buildx
script:
  - docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
  - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
  - bash build.sh