apiVersion: apps/v1
kind: Deployment
metadata:
  name: scoreboard-live
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      name: scoreboard-live
  template:
    metadata:
      labels:
        name: scoreboard-live
    spec:
      restartPolicy: Always
      containers:
      - name: frontend
        image: alex4108/scoreboard-frontend:GIT_SHA
        env:
        - name: BACKEND_HOST
          value: scoreboard-live-backend.default.svc.cluster.local
        ports:
        - containerPort: 80
          protocol: TCP
      - name: backend
        image: alex4108/scoreboard-backend:GIT_SHA
        env:
        - name: mongoConnectionString
          valueFrom:
            secretKeyRef:
              name: mongodb
              key: connection_string
              optional: false 
        - name: corsOrigin
          value: "*"
        ports:
        - containerPort: 8080
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: scoreboard-live
  namespace: default
spec:
  selector:
    name: scoreboard-live
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: scoreboard-live-backend
  namespace: default
spec:
  selector:
    name: scoreboard-live
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: ClusterIP